#!/bin/sh

. $ANDROID_BUILD_TOP/vendor/mallow/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5=md5
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
    exit 1
fi

if [ ! -z "$IS_RELEASED_BUILD" ]; then
   BUILD_PROP=$OUT/system/build.prop
   LAST_BUILD_PROP=$ANDROID_BUILD_TOP/last_build-$MALLOW_DEVICE.prop
   echo $CL_CYN"Copying '${BUILD_PROP}' to '${LAST_BUILD_PROP}'"$CL_RST
   cp $BUILD_PROP $LAST_BUILD_PROP
fi

exit 0
